discourse:
  image: codeformuenster/discourse
  ports:
    - "3000:3000"
  volumes:
    - discourse/assets:/usr/src/app/public/assets
    - discourse/uploads:/usr/src/app/public/uploads
  links:
    - postgres
    - redis
  env_file:
    - .env

sidekiq:
  image: codeformuenster/discourse
  command: sidekiq -c 3 -v
  links:
    - postgres
    - redis
  env_file:
    - .env

postgres:
  image: postgres:9.4
  environment:
    - POSTGRES_USER=discourse
  env_file:
    - .env
  volumes:
    - postgres/data:/var/lib/postgresql/data

redis:
  image: redis:2.6
