discourse:
  image: codeformuenster/discourse
  ports:
    - "3000:3000"
  volumes:
    - discourse/assets:/usr/src/app/public/assets
  links:
    - postgres
    - redis
  environment:
    - SECRET_TOKEN=1234HaCkFlEiScH1234HaCkFlEiScH1234HaCkFlEiScH
    - DISCOURSE_DB_PASSWORD=d15c0ur53
    - DISCOURSE_HOSTNAME=discourse.hackfleisch
    - DISCOURSE_SMTP_ADDRESS=smtp.mandrillapp.com
    - DISCOURSE_SMTP_PORT=587
    - DISCOURSE_SMTP_USER_NAME=user
    - DISCOURSE_SMTP_PASSWORD=apikey

sidekiq:
  image: codeformuenster/discourse
  command: sidekiq -c 3 -v
  links:
    - postgres
    - redis
  environment:
    - SECRET_TOKEN=1234HaCkFlEiScH
    - DISCOURSE_DB_PASSWORD=d15c0ur53
    - DISCOURSE_HOSTNAME=discourse.hackfleisch
    - DISCOURSE_SMTP_ADDRESS=smtp.mandrillapp.com
    - DISCOURSE_SMTP_PORT=587
    - DISCOURSE_SMTP_USER_NAME=user
    - DISCOURSE_SMTP_PASSWORD=apikey
    - DISCOURSE_DEVELOPER_EMAILS=CONFIGURE_ME

postgres:
  image: postgres:9.4
  environment:
    - POSTGRES_PASSWORD=d15c0ur53
    - POSTGRES_USER=discourse
  volumes:
    - postgres/data:/var/lib/postgresql/data

redis:
  image: redis:2.6
