discourse:
  image: codeformuenster/discourse
  ports:
    - "3000:3000"
  volumes:
    - discourse/assets:/usr/src/app/public/assets
  links:
    - postgres
    - redis
  env_file:
    - discourse_env

sidekiq:
  image: codeformuenster/discourse
  command: sidekiq -c 3 -v
  links:
    - postgres
    - redis
  env_file:
    - discourse_env

postgres:
  image: postgres:9.4
  env_file:
    - discourse_env
  volumes:
    - postgres/data:/var/lib/postgresql/data

redis:
  image: redis:2.6
