redis:
  image: redis:2.6

postgres:
  image: postgres:9.4
  environment:
    - POSTGRES_PASSWORD=d15c0ur53
    - POSTGRES_USER=discourse
  volumes:
    - ./pg_data:/var/lib/postgresql/data

discourse:
  build: .
  ports:
    - "3000:3000"
  volumes:
    - ./public/assets:/usr/src/app/public/assets
  links:
    - postgres
    - redis
#    - sidekiq
  environment:
    - RAILS_ENV=production
    - SECRET_TOKEN=1234HaCkFlEiScH
    - DISCOURSE_REDIS_HOST=redis
    - DISCOURSE_DB_HOST=postgres
    - DISCOURSE_DB_PASSWORD=d15c0ur53
    - DISCOURSE_SERVE_STATIC_ASSETS=true
    - DISCOURSE_HOSTNAME=discourse.hackfleisch
    - DISCOURSE_SMTP_ADDRESS=smtp.mandrillapp.com
    - DISCOURSE_SMTP_PORT=587
    - DISCOURSE_SMTP_USER_NAME=user
    - DISCOURSE_SMTP_PASSWORD=apikey
    - DISCOURSE_DEVELOPER_EMAILS=webwurst@gmail.com

sidekiq:
  build: .
  command: sidekiq -c 3 -v
  links:
    - postgres
    - redis
  environment:
    - RAILS_ENV=production
    - SECRET_TOKEN=1234HaCkFlEiScH
    - DISCOURSE_REDIS_HOST=redis
    - DISCOURSE_DB_HOST=postgres
    - DISCOURSE_DB_PASSWORD=d15c0ur53
    - DISCOURSE_SERVE_STATIC_ASSETS=true
    - DISCOURSE_HOSTNAME=discourse.hackfleisch
    - DISCOURSE_SMTP_ADDRESS=smtp.mandrillapp.com
    - DISCOURSE_SMTP_PORT=587
    - DISCOURSE_SMTP_USER_NAME=user
    - DISCOURSE_SMTP_PASSWORD=apikey
    - DISCOURSE_DEVELOPER_EMAILS=webwurst@gmail.com
